### ISSUE TITLE
Bug: nameof is not defined on Angular

### ISSUE THREAD

**Issue by nemu69** [Shinigami92/vite-ts-nameof#113]
## Info

| Tool                  | Version                 |
| --------------------- | ----------------------- |
| vite-plugin-ts-nameof | v^3.0.0                 |
| Vite                  | v^5.0.0                  |
| Node                  | v18.16.0                |
| OS                    | win        |

## Context
Compiler passed without issue but at runtime ERROR ReferenceError: nameof is not defined appears.

![image](https://github.com/Shinigami92/vite-plugin-ts-nameof/assets/43633395/aed35a2e-c3a8-4ee9-8703-7f617ec799d2)

Here my git for test: [Playground](https://github.com/nemu69/angularXts-nameof/tree/vite-plugin)
Thanks !

**Comment by nemu69** [comment]
Issue fixed.
https://github.com/typescript-nameof/nameof/issues/10#issuecomment-2030834053

**Comment by Shinigami92** [comment]
Is there anything we might want to document? So further people don't run into that problem?
If you want, you can contribute to the `README.md`
