### ISSUE TITLE
Add support for Vite 3.x.x

### ISSUE THREAD

**Issue by avenmore** [Shinigami92/vite-ts-nameof#94]
No longer able to use this plugin if using Vite 3 (3.0.4).

```
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0" from vite-plugin-ts-nameof@1.1.0

```

**Comment by Shinigami92** [comment]
Yes, make a release later this day 👍

**Comment by Shinigami92** [comment]
closed via https://github.com/Shinigami92/vite-plugin-ts-nameof/commit/703e13b9b441fa6c91461ee0439248ff7a5112c8

**Comment by Shinigami92** [comment]
@avenmore please test out v1.2.0 and report any issues (I haven't tested myself ^^')
If something broke, please re-open this issue and say what's wrong
Otherwise have a nice day :)

**Comment by avenmore** [comment]
Installed without problems and works perfectly with a dev build (can't test release atm). Thanks very much for attending to this so promptly :)
